name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: verilator/verilator
    steps:
    - uses: actions/checkout@v3
      
    - name: Run
      run: make run
