name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: verilator/verilator
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Run
      run: make run
