name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: verilator/verilator

    steps:
    - uses: actions/checkout@v3
      
    - name: Run
      run: make run
