name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: verilator/verilator:4.210
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Dependency
      run: apt-get update && apt-get install -y libreadline-dev
    - name: Run
      run: make run ARGS="-b -l build/log.txt"
